name: 'context example'

on:
  push:
    branches:
      - main

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Basic Information"
        run: |
          echo "REF: $GITHUB_REF"
          echo "Job ID: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"
      - name: "Echo context information"
        run: |
          echo "github.workspace: ${{ github.workspace }}"
          echo "github.sha: ${{ github.sha }}"
          echo "context.eventName: ${{ github.event_name }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.event: ${{ toJson(github.event) }}"